input parts/head;
input parts/corn;
input parts/body;
input parts/armour;
input parts/arm;
input parts/leg;
input parts/join;


def_part_g_h(g.h);

def_part_g_c(g.c);

def_part_g_w(g.w);
def_part_g_b(g.b);

def_part_g_s_l(g.s.l);
def_part_g_s_r(g.s.r);

def_part_g_a_u_l(g.a.u.l);
def_part_g_a_u_r(g.a.u.r);
def_part_g_a_l_l(g.a.l.l);
def_part_g_a_l_r(g.a.l.r);

def_part_g_l_l_l(g.l.l.l);
def_part_g_l_l_r(g.l.l.r);
