verbatimtex;
%&latex
\documentclass{article};
\begin{document};
etex;

input macros;
input config/parts;
input config/global;

input parts/head;
input parts/corn;
input parts/body;
input parts/armour.mp;
input parts/arm.mp;
input parts/leg;
input parts/join;

input config/offsets;
input config/positions;
input annotation;
input figures/overview.mp;
input figures/parts.mp;

verbatimtex;
\end{document};
etex;
end.
