./tests/builtin/m1.sh
./tests/builtin/m2.sh
./tests/builtin/m3.sh
./tests/builtin/m4.sh
./tests/builtin/m5.sh
./tests/builtin/p1.sh
./tests/builtin/s1.sh
./tests/builtin/cy-1.sh
./tests/builtin/cy-2.sh
./tests/builtin/cy-3.sh
